### ISSUE TITLE
Whitespace controll lint

### ISSUE THREAD

**Issue by lemingos** [Dealerdirect/liquid-linter-cli#3]
## Problem/Motivation

> linter error while parsing through whitespace tags
https://shopify.github.io/liquid/basics/whitespace/

## Expected behaviour

> should not raisee error on whitespace tag

## Actual behaviour

>   9:1-9:17  error  Tag '{%- if query -%}' was not properly terminated with regexp: undefined

## Steps to reproduce

> run linter on file with {%- -%}

## Proposed changes

> should accept tag with -

**Comment by Potherca** [comment]
Thank you for taking the time to report this issue!

The problem you report does not lie with this package but with the upstream linter ([tomheller/liquid-linter](https://github.com/tomheller/liquid-linter)).

To see this problem originate from the upstream package, take the following steps:

1. Create a file named `example.lqd` with the content: `{%- -%}`
2. Create a file named `main.js` with the content:
```
require('liquid-linter').lintFile('example.lqd', function(error) {
    var message = 'no issues found';
    if (error[0]) {
        message = error[0].message;
    }
    console.log(message);
});
```
3. Run `npm install --save liquid-linter` from the command-line
4.  Run `node main.js` from the command-line

This will give the following output:
```
Tag '{%- -%}' was not properly terminated with regexp: undefined
    at {%- -%} (undefined:1:1)
```
As you can see, the output of `liquid-linter-cli` is taken _directly_ from `liquid-linter`. Any weird output or incorrect linting should be [reported at the liquid-lint repository](https://github.com/tomheller/liquid-linter/issues).

An issue for this has been opened: https://github.com/tomheller/liquid-linter/issues/3, I would suggest reporting your problem there.
